import onstage from "@/assets/images/OnStage/onstage";
import CulturalFest from '../../assets/visualassets/CulturalFest.js';
const OnStageDetails = [
  {
    eventName: "Solo Singing",
    facultyCoordinator:
      "Ms. Ramsheena, AP/SH (Kindle Club)",
    facultyNumber: "9037319421",
    studentCoordinator: "PRISHA K, SARAVANA KUMAR. P ",
    studentNumber: "90423 73480, 63693 83477 ",
    venue: "LBS Hall",
    time: "9:30AM",
    description: [
      "Only Individual participants are allowed.",
      "Performance timing must be within 2-3 mins.",
      "Participant must bring instrument or instrumental music with self to perform. (Pen drive).",
      "Judgment will be based on tal, selection of raga, composition and general impression.",
      "The decision of the jury shall be final.",
      "Top six contestants will be selected to the final round.",
    ],
    image: CulturalFest.onstage.SoloSinging,
    reverse: false,
  },
  {
    eventName: "Solo Dance",
    facultyCoordinator:
      "Mr. Arun Kumar AP/ME (Riders Club)",
    facultyNumber: "+91 85264 08302",
    studentCoordinator: "•	Mr Vinish R, •	Mr Benial V",
    studentNumber: "6374542762, 8825503768",
    venue: "MG Hall",
    time: "9:30AM",
    description: [
      "Time limit for the performance will be 3 to 5 minutes.",
      "Any style of dance is accepted, but No Vulgar songs, dress and steps.",
      "If the Number of participants increases prelims time for every participant will be reduced.",
      "Props required for the performance must be brought by the participants. Usage of fire and glass as props is not encouraged.",
      "The participants are asked to bring the songs/track in pen-drive.",
      "The decision of the jury shall be final with regard to the interpretation of the rules.",
      "Top six contestants will be selected to final round.",
      "Participants should dress appropriately and avoid indecent exposure"
    ],
    image: CulturalFest.onstage.SoloDance,
    reverse: true,
  },
  {
    eventName: "Group Dance",
    facultyCoordinator:
      "Ms. Saranya, AP/ECE (Music and Dance Club)",
    facultyNumber: "9787865982",
    studentCoordinator: "MOHAN RAJ T, SANTHOSH P ",
    studentNumber: "8825960347, 6380431085",
    venue: "Auditorium",
    time: "10:00AM",
    description: [
      "Any style of dance is accepted, but No Vulgar songs, dress and steps.",
      "The Group must contain either girls or boys i.e., no mixed groups",
      "Each team must consist of minimum 4 and maximum 12 members.",
      "The performance duration should be between 3 to 5 minutes.",
      "No explicit or inappropriate lyrics are allowed.",
      "Use of hazardous materials (fire, water, sharp objects) is strictly prohibited.",
      "If the Number of participants increase prelims time for every team will be reduced",
      "Props required for the performance must be brought by the participants. Usage of fire and glass as props is not encouraged",
      "The participants are asked to bring their sounds/track in pen-drive.",
      "The participating team will be responsible for removal of their sets / properties etc. immediately after the completion of their performance.",
      "9.	Any misconduct, inappropriate behaviour, or use of offensive content will lead to disqualification",
      "Judgment will be based on the qualities like Tal, Technique, Rhythm, Abhinaya or Expression, Costumes, Footwork and general impression etc.",
    ],
    image: CulturalFest.onstage.GroupDance,
    reverse: false,
  },
  {
    eventName: "Instrumentals",
    facultyCoordinator:
      "Mr. Prabhu, AP/S&H (My Campus Clubs)",
    facultyNumber: "",
    studentCoordinator: "",
    studentNumber: "",
    venue: "Auditorium",
    time: "12:00PM",
    description: [
      "The team must contain a maximum of 8 members",
      "The Performance will last approximately 4-5 minutes",
      "Participants should bring their own musical instruments for the performance",
      "Maximum of 3 singers in a group and Number of accompanists playing instruments shall be six.",
      "Instruments of western origin adopted to the India Raga system are allowed",
      "Maximum time allowed for the instrumental music is 10 minutes which include setting time. The setting time for a group shall not exceed 4 minutes.",
      "Judgment will be made on the qualities like, composition rhythm, coordination and general impression.",
    ],
    image: CulturalFest.onstage.Drumbs,
    reverse: true,
  },
  {
    eventName: "Adapt Tune",
    facultyCoordinator:
      "Mr. Pradeep Kumar, AP/ CE(Riders Club)",
    facultyNumber: "+91 77083 50825",
    studentCoordinator: "M.E.ANDARDAKKAR, R. HARIHARASUTHAN",
    studentNumber: "6384302213, 8807439292",
    venue: "MG Hall",
    time: "1:00PM",
    description: [
      "Individual on-stage event.",
      "Time duration: 1-2 minutes",
      "Participants must adapt their dance styles to the music played.",
      "Judgment will be made base don expression, Choreography, Energy, and Attire.",
      "The decision of the jury shall be final with regard to the interpretation of the rules.",
    ],
    image: CulturalFest.onstage.AdaptTune,
    reverse: false,
  },
  {
    eventName: "Stand up",
    facultyCoordinator:
      "Ms. Charumathi, AP/S&H (Kindle Club)",
    facultyNumber: "+91 99943 76667",
    studentCoordinator: "",
    studentNumber: "",
    venue: "Academic Hall 2",
    time: "10:00AM",
    description: [
      "Variety events like mimicry, solo instrumentals, stand-up comedy, beatbox and others",
      "Each participant will be given 3-5 minutes to prove themselves",
      "Best talents will be awarded.",
      "MIMICRY:",
      "Each student artist shall be given 5 minutes time.",
      "Participants may mimic the sound of machines, speeches of a well-known persons etc.,",
      "Marks will be awarded based on skill imitating, variety of sound and voice imitation and presentation",
      "STAND-UP COMEDY:",
      "Only solo participants are allowed",
      "No participant may make any reference to individuals or religion and any dual meaning obscene content is strictly prohibited",
    ],
    image:  CulturalFest.onstage.standupcomedy,
    reverse: true,
  },
  {
    eventName: "Skit & Mime",
    facultyCoordinator:
      "Dr. S. Vignesh, ASP/CSE (Software Development Club)",
    facultyNumber: "+91 98946 42277",
    studentCoordinator: "Jeeva, Praveen",
    studentNumber: "+91 99526 07287, +91 94897 90927",
    venue: "Academic Hall 1",
    time: "10:00AM",
    description: [
      "MIME:",
      "Time duration: Maximum of 5 minutes",
      "Props and music is allowed.",
      "Their music should only contain instrumental and no lyrics.",
      "The act should not contain any dialogue or lip sync.",
      "Judgement will be based on innovation, depiction of the situation, team work and expressions.",
      "The decision of the jury shall be final with regard to the interpretation of the rules.",
      "SKIT:",
      "The teams will be free to select the theme/story/script of the skit",
      "Maximum of 8 and minimum of 4 participants will be allowed.",
      "The teams will be given 2-3 minutes time for arrangement of props.",
      "The team will be allowed to perform for 3-5 minutes",
      "Necessary props must be arranged by the participants",
      "Act will be judged based on the script, facial expression, stage presence, co-ordination, voice modulation and overall performance.",
    ],
    image:  CulturalFest.onstage.Mime,
    reverse: false,
  },
  {
    eventName: "Ethnic Walk",
    facultyCoordinator:
      "Ms . Adlin Princy(Kindle Club)",
    facultyNumber: "6369018498",
    studentCoordinator: "DIVYA BARATHI B, NANTHINI R T",
    studentNumber: "+ 9150125366,7826040476 ",
    venue: "Auditorium",
    time: "2:00PM",
    description: [
      "Each participant/ team will be given a minute on stage.",
      "Individual / Couple of participants will be permitted.",
      "Participants are asked not to wear any revealing cloths.",
      "Participants should bring their own cloths, makeup and accessories for the walk.",
      "Garments and accessories used for competition should depict the ethnicity of the country, state or any other culture.",
      "Any form of indecency, vulgarity, obscenity will result in disqualification.",
    ],
    image:  CulturalFest.onstage.EthnicWalk,
    reverse: true,
  },
  {
    eventName: "RJ/VJ Hunt",
    facultyCoordinator:
      "Dr. Saminathan, ASP/ EC(Tamil Mandram)",
    facultyNumber: "",
    studentCoordinator: "",
    studentNumber: "",
    venue: "KIC",
    time: "12:00PM",
    description: [
      "Only individual participants are allowed",
      "Participants have to prepare a script on the given topic at the time of the event",
      "Both Tamil and English languages can be used.",
      "Time limit will be 6 minutes (3min for preparation and 3min for presentation)",
      "Participants will be judged on the basis of scripts, presentation, voice modulation, voice quality",
    ],
    image:  CulturalFest.onstage.vjrj,
    reverse: false,
  },
  // {
  //   eventName: "Variety Event",
  //   facultyCoordinator:
  //     "Ms Monisha L, AP / SH(Tamil Mandram)",
  //   facultyNumber: "9003806038",
  //   studentCoordinator: "M.Azhagu akshaya, M.Bhoopesh ",
  //   studentNumber: "7810004627, 9445910290",
  //   venue: "Academic Hall 2",
  //   time: "1:00PM",
  //   description: [
  //     "Variety events like mimicry, solo instrumentals, stand-up comedy, beatbox and others",
  //     "Each participant will be given 3-5 minutes to prove themselves",
  //     "Best talents will be awarded.",
  //     "MIMICRY:",
  //     "Each student artist shall be given 5 minutes time.",
  //     "Participants may mimic the sound of machines, speeches of a well-known persons etc.,",
  //     "Marks will be awarded based on skill imitating, variety of sound and voice imitation and presentation",
  //     "STAND-UP COMEDY:",
  //     "Only solo participants are allowed",
  //     "No participant may make any reference to individuals or religion and any dual meaning obscene content is strictly prohibited",
  //   ],
  //   image: onstage.Variety,
  //   reverse: true,
  // },
  
];

export default OnStageDetails;
